<?php
include("../include/header.php");
include("../include/menu.php");
include("../include/get_element_vitrina.php");
$name_tovar = $element_vit_name_37;
$price_tovar = $element_vit_price_37;
$url_img_tovar = $element_vit_url_37;
$sklad_tovar = "10 шт";
$description_tovar = "Бытовой газовый двухконтурный настенный отопительный котел Beretta CITY 28 CSI мощностью 28 кВт с закрытой камерой сгорания и встроенной модулируемой газовой горелкой создан не только для обогрева домов, но и для организации горячего водоснабжения хозяйственно-бытового назначения. Воздух для горения котла поступает с улицы через коаксиальную трубу. Два раздельных пластинчатых теплообменника не подвержены коррозии: стальной - для отопления и из нержавеющей стали - на ГВС. Данная модель менее требовательна к качеству поступающей воды и оснащена всем необходимым оборудования для быстрого монтажа и включения.

 

Раздельные теплообменники контура отопления и ГВС (для моделей CITY CSI);
ЖК- дисплей на панели управления;
Возможность работы в конденсационном режиме с КПД достигающем 108% (для модели CITY 50 RSI green);
Два отверстия для подключения воздуховодов при раздельном дымоудалении и воздухозаборе (для моделей CITY CSI-RSI);
Возможность получения сигнала о блокировке для передачи его на расстояние (с использованием дополнительного аксессуара);
Возможность подключения отдельно стоящего бойлера-аккумулятора ГВС (для моделей RSI);
Трехскоростной циркуляционный насос GRUNDFOS;
Возможность управления внешним трехходовым клапаном контура ГВС (для модели CITY 50 RSI green);
Встроенная функция погодозависимого регулирования (при установке датчика наружной температуры). Для CITY 50 RSI green датчик наружной температуры поставляется в комплекте;
Плавная регулировка мощности (модуляционная горелка);
Встроенный трехходовой клапан контура ГВС (для моделей CITY RSI) (кроме CITY 50 RSI green);
Автоматический электророзжиг и ионизационный контроль пламени;
Приоритет горячего водоснабжения;
Встроенная функция защиты от замерзания и блокировки насоса и трехходового клапана;
Система самодиагностики неисправностей с выводом информации на ЖК-дисплей;
Встроенная функция автоматической регулировки температуры теплоносителя (при подключении комнатного термостата);
 Возможность подключения пульта дистанционного управления;
Возможность работы на сжиженном нефтяном газе.";
?>

<div class="main_page">
		<?php	include("../include/sidebar_vodonagrev.php"); ?>
	<div class="main_content">
		<div class="cart">
			<div class="cart_title">
				<h2><?php echo $name_tovar; ?></h2>
			</div>
			<div class="cart_right">
				<div class="cart_img">
					<a href=""><img alt="$name_tovar" src="<?php echo $url_img_tovar; ?>"></a>
				</div>
				<div class="cart_price">
					<div class="price">Цена <?php echo $price_tovar; ?>  Руб</div>
					<span>На складе <?php echo $sklad_tovar; ?></span>
					<button class="open-button" onclick="openForm()">Купить в один клик</button>
					<!-- <a class="button_buy2 basket_submit_button" href="#add_cart" >Купить в один клик</a> -->
					<div class="form-popup" id="myForm">
					  <form action="../sendform.php" method="post" class="form-container">
					    <h2>Оставьте ваши данные<br> и мы с вами свяжемся:</h2>
					    Ваш товар <br><input type="text" name="name_tovar" value='<?php echo $name_tovar; ?>'><br>
					    Ваше имя <br><input type="text" name="first_name"><br>
					    Email: <br><input type="text" name="email" required placeholder="Обязательное поле"><br>
						Номер телефона:<br><input type="text" name="number" required placeholder="Обязательное поле"><br><br>
					    <input type="submit" id="addButton3" name="submit" value="Отправить">
					    <button type="button" class="btn cancel" onclick="closeForm()">Закрыть</button>
					  </form>
					</div>
				</div>
			</div>
			<div class="cart_info">

				<input class="button_stock button_active" type="button" id="addButton"  value="Описание">
				<input class="button_stock" type="button" id="addButton1" value="Технические характеристики">
				<input class="button_stock" type="button" id="addButton2"  value="Документация и сертификаты">

				<div id="text1" class="text">
					<div class="text" id="description_2782_idm14763792"><p><?php echo $description_tovar; ?></p>
					<h2 style="text-align: center;">Купить  <?php echo $name_tovar; ?></h2>
					<p style="text-align: center;">можно у нас на сайте на прямую нажав на кнопку "Заказать", либо же позвонив по&nbsp;телефону&nbsp;и задать нашим специалистам все интересующие вопросы:&nbsp;</p>
					<p style="text-align: center;">&nbsp;<?php echo $number_one; ?></p></div>
				</div>
				<div id="text2" class="text">
<div class="ckTable">
                        
        <div class="list-dotted list-dotted-2 full" font-size:="" pt="" style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: ">
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; text-align: center;">
		<span style="font-size:20px;"><strong><span font-size:="" pt="">Технические характеристики</span></strong></span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Тип котла</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Газовый</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Принцип работы</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Конвекционный</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Кол-во контуров</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Двухконтурный</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Способ крепления</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Настенный</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Тип камеры сгорания</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Закрытая</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Тепловая мощность, кВт</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">28</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Встроенный расширительный бак</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Встроенный циркуляционный насос</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Природный газ</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Сжиженный газ</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Диаметр коаксиального дымохода, мм</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">60/100, 80/125</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Материал первичного теплообменника</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Медь</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Дисплей</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Управление</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Электронное</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Производитель</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Италия</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Давление в расширительном баке, бар</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">1</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Диаметры коаксиального дымохода</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">60/100 / 80/125</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Кол-во форсунок, шт</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">11</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Макс. давление воды /макс.температура в контуре отопления, бар/°С</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">3/90</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Макс. давление воды в контуре ГВС, бар</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">6</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Макс.длина коаксиального дымоотвода, м</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">3,4 / 10</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Минимальная тепловая мощность, кВт</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">8.9</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Массовый расход дымовых газов (макс.- мин.), г/с</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">18,21 - 19,7</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Мин. давление для стандартной работы в режиме ГВС, бар</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">0.15</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Мин. давление для стандартной работы в режиме отопления, бар</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">0,25 - 0,45</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Мин. давление на горелке, мбар</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">1.5</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Патрубок подключения контура ГВС, дюйм</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">1/2</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Минимальная тепловая производительность, кВт</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">7.52</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Минимальный расход воды, л/мин</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">2</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Напряжение сети и частота электропитания, В/Гц</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">230/50</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Насос: макс.допустимый напор для системы при расходе 1000 л/ч, мбар</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">240</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Номинальная тепловая мощность в режиме отопления/ГВС, кВт</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">25,8</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Номинальная тепловая производительность в режиме отопления/ГВС, кВт</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">23,94</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Номинальное давление газа метана G20, мбар</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">20</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Ограничитель потока, л/мин</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">10</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Отверстие при проходе через стену, Ø мм</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">105 / 130</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Подключение раздельного дымохода (Ø 80 мм)</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Полезный КПД, %</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">91.8</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Потери на отводе 45°/90°, м</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">1/1,5 / 1,35/2,2</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Потери тепла через дымоход при отключенной горелке, %</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">0.15</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Производительность горячей воды при t 25°C, л/мин</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">13.7</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Производительность горячей воды при t 30°C, л/мин</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">11.4</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Производительность горячей воды при t 35°C, л/мин</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">9.8</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Расход газа G20, м3/ч</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">1,11 - 3,23</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Степень защиты IP</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">X5D</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Фильтр для газа</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Номинальное давление сжиженного газа бутана G30/ пропана G31, мбар</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">28 - 30/37</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Расход газа G30, м3/ч</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">0,83 - 2,4</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Расход газа G31, м3/ч</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">0,82 - 2,37</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Макс.длина коаксиального дымоотвода Ø 80, м</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">14,5+14,5</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Потери на отводе 45°/90° Ø 80, м</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">0,5/0,8</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Электрическая мощность, Вт</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">115</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Защита от перегрева</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Индикация включения</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Температура в контуре ГВС, °С</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">37 - 60</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Температура теплоносителя, °С</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">40 - 80</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Размеры (ШхВхГ), мм</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">405 х 715 х 248</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Вес, кг</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">33</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Защита от замерзания</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Класс Nox</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">3</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Предохранительный клапан</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Теплообменник</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Раздельный</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Емкость расширительного бака, л</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">8</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Автодиагностика</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Воздухоотводчик</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Газ-контроль</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Защита от блокировки насоса</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Манометр</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Термометр</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Автоподжиг</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Модуляция пламени</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">Да</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Патрубок подключения газа, дюйм</span><span class="p_val" style="box-sizing: border-box; display: inline-block; background: inherit; position: absolute; bottom: 0px; left: auto; right: 0px; width: auto; padding: 0px 0px 0px 4px; text-align: right; z-index: 2;">3/4</span></div>
	<div class="single-param" style="box-sizing: border-box; position: relative; width: 762.469px; margin-bottom: 7px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
		<p>
			<span class="p_name" style="box-sizing: border-box; display: inline; background: inherit; position: relative; bottom: 0px; z-index: 1; padding: 0px 4px 0px 0px;">Патрубок подключения контура отопления, дюйм&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="background-color: inherit; text-align: right;">3/4</span></p>
		<p>
			&nbsp;</p>
		<div>
			<span style="font-size:26px;">Цена:&nbsp; &nbsp; &nbsp;<strong style="text-align: center;"><span style="color: rgb(0, 0, 0);"><span new="" style="font-family: " times="">53436.00 РУБ</span></span></strong></span></div>
	</div>
</div>

            </div>
				
				</div>
				<div id="text3" class="text">
					<a href="https://krimteploservis.com/files/brandrelations/Сертификат%20соответствия%20котел%20Beretta%2011.05.2019%20г..pdf">Сертификат</a>
					 +7 (495) 984-52-34
				</div>
		</div>

	</div>
<?php
include("../include/footer.php");
?>